# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31bb412bb9b1f217b81a4f534e4f918d516f7a0baaebf7ad9a95fbd1323fecf0894a113818b87cd471a85f41ebfe63d6a1835bb470ad40444fbacb65e5fc5533

test:
  secret_key_base: bb575756968e9cc4f237fc467fdc17fe88fd62a449206adedfc6b8c04430b691ab5f1c2bb8b04cfb3c543703bffc591d40c0732ec7e752406e72a4bc1c9dc14b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
